#!/usr/bin/env bash

set -euo pipefail

# REPO e.g. FluxML/NNlib.jl
REPO=${BUILDKITE_PLUGIN_GITHUB_COMMENT_REPOSITORY}
PR=${BUILDKITE_PLUGIN_GITHUB_COMMENT_ISSUE_NUMBER}

buildkite-agent artifact download comment.txt .
COMMENT=$(cat comment.txt)
echo $COMMENT

if [[ -z "${REPO:-}" ]]; then
  echo "Error: REPO is missing. Skipping" 1>&2
  exit 1
fi

if [[ -z "${PR:-}" ]]; then
  echo "Error: PR to comment is missing. Skipping" 1>&2
  exit 1
fi

if [[ -z "${COMMENT:-}" ]]; then
  echo "Error: comment property in the plugin es mandatory" 1>&2
  exit 1
fi

if [[ -z "${PEM_CONTENT_B64:-}" ]]; then
  echo "Error: PEM_CONTENT_B64 environment variable not set"  1>&2
  echo "A Github App private key (*.pem) encoded with base64 is needed to generate 'Installation Access Token'" 1>&2
  exit 1
fi

if [[ -z "${APP_ID:-}" ]]; then
  echo "Error: APP_ID environment variable not set"  1>&2
  echo "An App ID is needed to generate 'Installation Access Token'" 1>&2
  exit 1
fi

if [[ -z "${INSTALLATION_ID:-}" ]]; then
  echo "Error: INSTALLATION_ID environment variable not set"  1>&2
  echo "An Installation ID is needed to generate 'Installation Access Token'" 1>&2
  exit 1
fi

# Try to get python3 if installed
python_bin="python3"
if ! [[ -x "$(command -v ${python_bin})" ]]; then
  python_bin="python"
fi
${python_bin} -m pip install jwt

# Generate JWT
JWT=$(${python_bin} hooks/get_jwt.py ${PEM_CONTENT_B64} ${APP_ID})

# Generate Installation Access Token
IAT=$(curl -L -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${JWT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/app/installations/${INSTALLATION_ID}/access_tokens | jq -r ".token")


if [[ -z "${IAT:-}" ]]; then
  echo "Error: IAT failed to be generated"  1>&2
  echo "A Github Installation Access Token with correct permissions is needed to comment on issue" 1>&2
  exit 1
fi

echo "Posting comment to #$PR in $REPO"  1>&2

jq -n --arg msg "${COMMENT}" '{body: $msg}' | curl -sSg \
    -u apikey:${IAT} \
    -H 'Accept: application/vnd.github.v3+json' \
    -H 'Content-Type: application/json' \
    -X POST \
    -d@- \
    "https://api.github.com/repos/${REPO}/issues/${PR}/comments"
